### ISSUE TITLE
netcoreapp2.1 target framework

### ISSUE THREAD

**Issue by AlexTalcura** [reinforced/Reinforced.Typings#68] opened 2018-06-06 03:44 UTC
Can you please add .Net Core 2.1 build target? Right now this library works perfectly with .Net Core 2.0 but triggers the following error:

<removed>\.nuget\packages\reinforced.typings\1.4.92\build\Reinforced.Typings.targets(79,3): error MSB6006: "" exited with code 1.

**Comment by pavel-b-novikov** [comment] 2018-06-06 04:06
Duplicate of #64

**Closed by pavel-b-novikov** 2018-06-06 04:06 UTC

**Comment by AlexTalcura** [comment] 2018-06-06 04:12
Just to confirm, this issue is regarding .Net Core 2.1, not 2.0

You can easily reproduce this issue using the following steps:

1. Create a new .Net Core 2.0 web app.
2. Add Reinforced.Typings nuget package and config file.
3. Mark any class e.g. with [TsClass]
4. Build -> you will see the generated file in the scripts folder.
5. Change framework to .Net Core 2.1
6. Build -> error

**Comment by pavel-b-novikov** [comment] 2018-06-06 04:15
I know, yes. We have discussed enough in #64

**Comment by AlexTalcura** [comment] 2018-06-06 04:20
Yes, looks like I was blind and didn't notice #65 and was a little bit confused when you've marked this issue as a duplicate for #64.

Anyway, thank you for your work! I will monitor #65 to see once it will be resolved.
